/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stm32f407xx.h>
#include "gpio_drv.h"
#include "gpio_exti_drv.h"

GPIO_Handle_t green_led_pin;
GPIO_EXTI_Handle_t user_btn_pin, falling_edge_trig_test;

void toggleLed(void)
{
	gpio_drv_Toggle(&green_led_pin);
}

int main(void)
{
	/* Green Led Output Pin */
	gpio_drv_PeripheralClockControl(GPIOD, true);
	gpio_drv_Init(&green_led_pin, GPIOD, 12, _GPIO_PIN_MODE_OUTPUT, _GPIO_PIN_OUTPUT_PUSH_PULL,
		_GPIO_PIN_OUTPUT_LOW_SPEED, _GPIO_PIN_NO_PULL_UP_PULL_DOWN, 0);

	/* User Button Init Pin As EXTI */
	gpio_drv_PeripheralClockControl(GPIOA, true);
	gpio_drv_PeripheralClockControl(GPIOC, true);

	gpio_exti_drv_Init(&user_btn_pin, GPIOA, 0, _GPIO_PIN_PULL_DOWN, _GPIO_EXTI_PIN_TRIG_RISING_EDGE, 0, toggleLed);
	gpio_exti_drv_Init(&falling_edge_trig_test, GPIOC, 6, _GPIO_PIN_PULL_UP, _GPIO_EXTI_PIN_TRIG_FALLING_EDGE, 0, NULL);

	for(;;)
	{
	}
}

void EXTI0_IRQHandler(void)
{
	gpio_exti_drv_IRQHandler(&user_btn_pin);
}

void EXTI9_5_IRQHandler(void)
{
	gpio_exti_drv_IRQHandler(&falling_edge_trig_test);
}
